(define (problem merry1)
	(:domain merry)
	(:objects
		n1 n2 n3 n4 n5
		r1
		p1 p2
		z1 z2 z3 z4
		c1 c2
		a b c d e f g h i
		pu1 pu2 pu3 pu4 pu5 pu6 pu7 pu8 pu9
		pk1 pk2 pk3 pk4 pk5 pk6 pk7 pk8
	)
	(:init
		(pokoj a)
		(pokoj b)
		(pokoj c)
		(pokoj d)
		(pokoj e)
		(pokoj f)
		(pokoj g)
		(pokoj h)
		(pokoj i)
		
		(klucz n1 f)
		(klucz n2 f)
		(klucz n3 i)
		(klucz n4 e)
		(klucz n5 c)
		
		(klucz r1 b)

		(klucz p1 i)
		(klucz p2 c)
		
		(klucz z1 h)
		(klucz z2 e)
		(klucz z3 a)
		(klucz z4 d)
		
		(klucz c1 h)
		(klucz c2 d)
		
		(drzwi a b p1)
		(drzwi a b p2)
		
		(drzwi a c c1)
		(drzwi a c c2)
		
		(drzwi b d p1)
		(drzwi b d p2)
		
		(drzwi c a c1)
		(drzwi c a c2)
		(drzwi c e z1)
		(drzwi c e z2)
		(drzwi c e z3)
		(drzwi c e z4)
		
		(drzwi d f z1)
		(drzwi d f z2)
		(drzwi d f z3)
		(drzwi d f z4)
		
		(drzwi e c z1)
		(drzwi e c z2)
		(drzwi e c z3)
		(drzwi e c z4)
		(drzwi e f n1)
		(drzwi e f n2)
		(drzwi e f n3)
		(drzwi e f n4)
		(drzwi e f n5)
		(drzwi e h c1)
		(drzwi e h c2)
		
		(drzwi f g r1)
		(drzwi f d z1)
		(drzwi f d z2)
		(drzwi f d z3)
		(drzwi f d z4)
		(drzwi f e n1)
		(drzwi f e n2)
		(drzwi f e n3)
		(drzwi f e n4)
		(drzwi f e n5)
		(drzwi f i n1)
		(drzwi f i n2)
		(drzwi f i n3)
		(drzwi f i n4)
		(drzwi f i n5)
		
		(drzwi h e c1)
		(drzwi h e c2)
		(drzwi h i n1)
		(drzwi h i n2)
		(drzwi h i n3)
		(drzwi h i n4)
		(drzwi h i n5)
		
		(drzwi i f n1)
		(drzwi i f n2)
		(drzwi i f n3)
		(drzwi i f n4)
		(drzwi i f n5)
		(drzwi i h n1)
		(drzwi i h n2)
		(drzwi i h n3)
		(drzwi i h n4)
		(drzwi i h n5)
		
		(bohater f)
		
		(sasiaduje pu1 pu2)
		(sasiaduje pu1 pu4)
		(sasiaduje pu2 pu3)
		(sasiaduje pu2 pu1)
		(sasiaduje pu2 pu5)
		(sasiaduje pu3 pu2)
		(sasiaduje pu3 pu6)
		(sasiaduje pu4 pu1)
		(sasiaduje pu4 pu5)
		(sasiaduje pu4 pu7)
		(sasiaduje pu5 pu2)
		(sasiaduje pu5 pu4)
		(sasiaduje pu5 pu6)
		(sasiaduje pu5 pu8)
		(sasiaduje pu6 pu3)
		(sasiaduje pu6 pu5)
		(sasiaduje pu6 pu9)
		(sasiaduje pu7 pu4)
		(sasiaduje pu7 pu8)
		(sasiaduje pu8 pu5)
		(sasiaduje pu8 pu7)
		(sasiaduje pu8 pu9)
		(sasiaduje pu9 pu6)
		(sasiaduje pu9 pu8)
		
		(pozycja pk1 pu3)
		(pozycja pk2 pu8)
		(pozycja pk3 pu6)
		(pozycja pk4 pu2)
		(pozycja pk5 pu1)
		(pozycja pk6 pu9)
		(pozycja pk7 pu7)
		(pozycja pk8 pu4)
		(wolne pu5)
	)
	(:goal
		(and
			(pozycja pk1 pu1)
			(pozycja pk2 pu2)
			(pozycja pk3 pu3)
			(pozycja pk4 pu4)
			(pozycja pk5 pu5)
			(pozycja pk6 pu6)
			(pozycja pk7 pu7)
			(pozycja pk8 pu8)
			(bohater g)
		)
	)

)