package com.sample
 
import com.sample.Plec;
import com.sample.Osoba;
import com.sample.Relacja;
 
rule "Init"
	when
	then
		Osoba maria          = new Osoba("Maria");
		Osoba ewa            = new Osoba("Ewa");
		Osoba agata          = new Osoba("Agata");
		Osoba anna           = new Osoba("Anna");
		Osoba agnieszka      = new Osoba("Agnieszka");
		Osoba beata          = new Osoba("Beata");
		Osoba iwona          = new Osoba("Iwona");
		Osoba joanna         = new Osoba("Joanna");
		Osoba piotr          = new Osoba("Piotr");
		Osoba adam           = new Osoba("Adam");
		Osoba marek          = new Osoba("Marek");
		Osoba robert         = new Osoba("Robert");
		Osoba jan            = new Osoba("Jan");
		Osoba krzysztof      = new Osoba("Krzysztof");
		Osoba radek          = new Osoba("Radek");
		Osoba darek          = new Osoba("Darek");
		Osoba tomek          = new Osoba("Tomek");
		Osoba jacek          = new Osoba("Jacek");

		insert(new Relacja(maria,marek,"rodzic"));
		insert(new Relacja(maria,agata,"rodzic"));
		insert(new Relacja(maria,jan,"rodzic"));
		insert(new Relacja(piotr,marek,"rodzic"));
		insert(new Relacja(piotr,agata,"rodzic"));
		insert(new Relacja(piotr,jan,"rodzic"));
		insert(new Relacja(ewa,anna,"rodzic"));
		insert(new Relacja(ewa,joanna,"rodzic"));
		insert(new Relacja(ewa,krzysztof,"rodzic"));
		insert(new Relacja(adam,anna,"rodzic"));
		insert(new Relacja(adam,joanna,"rodzic"));
		insert(new Relacja(adam,krzysztof,"rodzic"));
		insert(new Relacja(agata,radek,"rodzic"));
		insert(new Relacja(agata,beata,"rodzic"));
		insert(new Relacja(robert,radek,"rodzic"));
		insert(new Relacja(robert,beata,"rodzic"));
		insert(new Relacja(anna,darek,"rodzic"));
		insert(new Relacja(anna,tomek,"rodzic"));
		insert(new Relacja(jan,darek,"rodzic"));
		insert(new Relacja(jan,tomek,"rodzic"));
		insert(new Relacja(agnieszka,jacek,"rodzic"));
		insert(new Relacja(agnieszka,iwona,"rodzic"));
		insert(new Relacja(krzysztof,jacek,"rodzic"));
		insert(new Relacja(krzysztof,iwona,"rodzic"));
end

rule "Kobieta - pierwsze"
	when
		p: Relacja(osoby[0].imie.endsWith("a") && osoby[0].plec == Plec.NIEZNANA && osoby[0].relacje.contains(p));
	then
		p.osoby[0].plec = Plec.KOBIETA;
		p.osoby[0].relacje.remove(p);
		update(p);
		System.out.println(p.osoby[0].imie);
		for(Relacja r1: p.osoby[0].relacje){
			update(r1);
		}
end;

rule "Kobieta - drugie"
	when
		p: Relacja(osoby[1].imie.endsWith("a") && osoby[1].plec == Plec.NIEZNANA && osoby[1].relacje.contains(p));
	then
		p.osoby[1].plec = Plec.KOBIETA;
		p.osoby[1].relacje.remove(p);
		update(p);
		System.out.println(p.osoby[1].imie);
		for(Relacja r1 : p.osoby[1].relacje){
			update(r1);
		}
end;	

rule "Mezczyzna - pierwsze"
	when
		p: Relacja(!osoby[0].imie.endsWith("a") && osoby[0].plec == Plec.NIEZNANA && osoby[0].relacje.contains(p));
	then
		p.osoby[0].plec = Plec.MEZCZYZNA;
		p.osoby[0].relacje.remove(p);
		update(p);
		System.out.println(p.osoby[0].imie);
		for(Relacja r1 : p.osoby[0].relacje){
			update(r1);
		}
end;

rule "Mezczyzna - drugie"
	when
		p: Relacja(!osoby[1].imie.endsWith("a") && osoby[1].plec == Plec.NIEZNANA && osoby[1].relacje.contains(p));
	then
		p.osoby[1].plec = Plec.MEZCZYZNA;
		p.osoby[1].relacje.remove(p);
		update(p);
		for(Relacja r1 : p.osoby[1].relacje){
			update(r1);
		}
end;	

rule "Matka"
	when
		p: Relacja(osoby[0].plec == Plec.KOBIETA && relacja == "rodzic")
	then
		System.out.println("Matka: " + p.osoby[0].imie + ", Dziecko: " + p.osoby[1].imie);
		insert(new Relacja(p.osoby[0], p.osoby[1], "matka"));
end;

rule "Ojciec"
	when
		p: Relacja(osoby[0].plec == Plec.MEZCZYZNA && relacja == "rodzic")
	then
		System.out.println("Ojciec: " + p.osoby[0].imie + ", Dziecko: " + p.osoby[1].imie);
		insert(new Relacja(p.osoby[0], p.osoby[1], "ojciec"));
end;

rule "Babcia"
	when
		rodzic: Relacja(relacja == "rodzic");
		babcia: Relacja(osoby[0].plec == Plec.KOBIETA && relacja == "rodzic", osoby[1] == rodzic.osoby[0]);
	then
		System.out.println("Babcia: " + babcia.osoby[0].imie + ", wnuk: " + rodzic.osoby[1].imie);
		insert(new Relacja(babcia.osoby[0], rodzic.osoby[1], "babcia")); 
end;

rule "Dziadek"
	when
		rodzic: Relacja(relacja == "rodzic");
		dziadek: Relacja(osoby[0].plec == Plec.MEZCZYZNA && relacja == "rodzic", osoby[1] == rodzic.osoby[0]);
	then
		System.out.println("Dziadek: " + dziadek.osoby[0].imie + ", wnuk: " + rodzic.osoby[1].imie);
		insert(new Relacja(dziadek.osoby[0], rodzic.osoby[1], "dziadek")); 
end;

rule "Brat"
	when
		brat: Relacja(osoby[1].plec == Plec.MEZCZYZNA && relacja == "rodzic" && osoby[0].plec == Plec.MEZCZYZNA);
		rodzenstwo: Relacja(relacja == "rodzic" && osoby[0] == brat.osoby[0] && this != brat);
	then
		System.out.println("Brat: " + brat.osoby[1].imie + ", rodzenstwo: " + rodzenstwo.osoby[1].imie);
		insert(new Relacja(brat.osoby[1], rodzenstwo.osoby[1], "brat"));
end;

rule "Siostra"
	when
		siostra: Relacja(osoby[1].plec == Plec.KOBIETA && relacja == "rodzic" && osoby[0].plec == Plec.KOBIETA);
		rodzenstwo: Relacja(relacja == "rodzic" && osoby[0] == siostra.osoby[0] && this != siostra);
	then
		System.out.println("Siostra: " + siostra.osoby[1].imie + ", rodzenstwo: " + rodzenstwo.osoby[1].imie);
		insert(new Relacja(siostra.osoby[1], rodzenstwo.osoby[1], "siostra"));	 
end;

rule "Stryj"
	when
		brat_ojciec: Relacja(relacja == "brat");
		ojciec_dzieckco: Relacja(relacja == "ojciec" && osoby[0] == brat_ojciec.osoby[1]);
	then
		System.out.println("Stryj: " + brat_ojciec.osoby[0].imie + ", dziecko: " + ojciec_dzieckco.osoby[1].imie);
		insert(new Relacja(brat_ojciec.osoby[0], ojciec_dzieckco.osoby[1], "stryj"));
end;

rule "Wuj"
	when
		brat_matka: Relacja(relacja == "brat");
		matka_dziecko: Relacja(relacja == "matka" && osoby[0] == brat_matka.osoby[1]);
	then
		System.out.println("Wuj: " + brat_matka.osoby[0].imie + ", dziecko: " + matka_dziecko.osoby[1].imie);
		insert(new Relacja(brat_matka.osoby[0], matka_dziecko.osoby[1], "wuj"));	
end;

query "q_stryj"
    qs : Relacja(relacja == "stryj");
end

query "q_wuj"
    qw : Relacja(relacja == "wuj");
end